### 课程信息查询
POST {{content_host}}/content/course/list?pageNo=1&pageSize=10
Content-Type: application/json

{
  "auditStatus": "",
  "courseName": "",
  "publishStatus": ""
}

### 课程分类信息
GET {{content_host}}/content/course-category/tree-nodes

### 创建课程
POST {{content_host}}/content/course
Content-Type: application/json

{
  "charge": "201000",
  "price": 0,
  "originalPrice":0,
  "qq": "22333",
  "wechat": "223344",
  "phone": "13333333",
  "validDays": 365,
  "mt": "1-1",
  "st": "1-1-1",
  "name": "小肥",
  "pic": "",
  "teachmode": "200002",
  "users": "1-1",
  "tags": "",
  "grade": "204001",
  "description": ""
}

### 课程计划删除
DELETE {{content_host}}/content/teachplan/282

### delete media
DELETE {{gateway_host}}/media/23f83ae728bd1269eee7ea2236e79644




















